### ISSUE TITLE
Hardware Suggestion: MCP23017 & TCA9548A

### ISSUE THREAD

**Issue by abrilevskiy** [koriwi/freedeck-hardware#26]
I propose to use MCP23017/MCP23008 - an I2C port extender to handle button press via interrupts
and use TCA9548A (or similar) as an OLED screen multiplexer.

**Comment by koriwi** [comment]
Can you elaborate what improvements we will get from that? because the i2c multiplexer is much more expensive and i dont know if it will be compatible with the i2c bitbanging we are using.

Also i dont think we can use the i2c port extender with the bitbanging or we would have to implement a minimum lib by ourselves.

Also the normal analog multiplexers work and are much cheaper and easier to get around the world
